LinguistAI/mobile

- app.json
- components/common/Splash.tsx
- package-lock.json
- package.json
- screens/chat/ChatScreen.tsx
- screens/common/LandingScreen.tsx
- Added a splash to be shown during initial authentication
- Removed projectID from app.json
> [LINGUIST-117] Added a splash to be shown during initial authentication

- hooks/useUser.ts
- redux/chatSlice.ts
- Resets RTK cache when a user logs out because when a user logged out and logged in another account the data was not refreshed.
> fix(LINGUIST-379) Reset RTK cache on logout

- components/user/profile/FriendSearchProfileCard.tsx
- components/user/profile/friends/FriendProfileCard.tsx
- components/user/profile/friends/FriendRequestCard.tsx
- components/user/profile/friends/FriendsList.tsx
- components/user/profile/friends/FriendsSearchList.tsx
- components/user/types.ts
- components/user/userApi.ts
- eas.json
- hooks/useUser.ts
- screens/user/FriendRequestsScreen.tsx
- Refresh on friends & friend requests screen
- Removed emails on lists
> feat(LINGUIST-380 & LINGUIST-370) Added refresh & removed email info

- components/word-bank/word-list/WordLists.tsx
- components/word-bank/word-list/words/WordDetailsCollapse.tsx
- screens/word-list/WordListDetailsScreen.tsx
> fix(LINGUIST-382): Add keys to worddetail to get rid of console.warning

- components/word-bank/WordAddContainer.tsx
- redux/chatSlice.ts
- LINGUIST-381 Render error: I found the solution here: https://stackoverflow.com/questions/55622768/uncaught-invariant-violation-rendered-more-hooks-than-during-the-previous-rende
- LINGUIST-374 Word adding error: The problem was that even if we set the selectedWordList correctly, sometimes its id came up as undefined so the backend could not add the word to the list.
I tested these and they seem to work, but since these bugs only appeared _sometimes_ it would be better if someone else tried it on their app as well.
> fix(LINGUIST-381) & fix(LINGUIST-374): Fix word list render error and word adding error

- components/quiz/QuizResults.tsx
- redux/store.ts
> [LINGUIST-313] Add quizApi to redux store

- components/quiz/QuizResults.tsx
- Added correct info to quiz results page if an answer was incorrect
> [LINGUIST-313] Display correct answer in quiz results page

- components/common/form/OptionGroup.tsx
- components/user/constants.ts
- components/user/onboarding/PostRegistrationConversation.tsx
Minor changes to onboarding:
- After user selects a date, the message shown is: "I was born on 4/17/2024"
- Name is skippable
- If the user does not choose any hobby (but does not skip either), the message is "Nothing much"
- English level is changed to print the label (e.g., from BEGINNER to Beginner)
> fix(LINGUIST-367): User friendly onboarding

- components/common/form/ItemGroup.tsx
- components/common/form/PrimaryTextInput.tsx
- components/user/onboarding/UserInfoForm.tsx
- Added likes, dislikes, hates, loves to defaultvalues.
- Added onChange handlers
> [LINGUIST-328] Fix hobbies handled incorrectly by the form during update

- components/common/form/ItemGroup.tsx
- components/user/onboarding/UserInfoForm.tsx
- components/user/types.ts
> fix(LINGUIST-414): ML profile items can be deleted

- components/chat/bots/BotCarousel.tsx
- components/chat/bots/BotLists.tsx
- components/chat/conversations/ConversationList.tsx
- components/gamification/api.ts
- components/gamification/experience/ExperienceBar.tsx
- components/gamification/streak/ChatStreakContainer.tsx
- components/quest/QuestProgressBar.tsx
- components/quest/QuestsList.tsx
- components/quest/api.ts
- components/user/profile/Profile.tsx
- components/word-bank/WordAddContainer.tsx
- components/word-bank/WordInfoCard.tsx
- components/word-bank/word-list/WordLists.tsx
- components/word-bank/word-list/words/WordDetailsCollapse.tsx
- hooks/useChatMessages.ts
- screens/chat/ChatScreen.tsx
- screens/leaderboard/FriendsLeaderboardScreen.tsx
- screens/word-list/WordListDetailsScreen.tsx
- Replaced isFetching with isLoading. Data is refetched but the skeletons and loading indicators are only shown on the first try.
> [LINGUIST-434] Replace isFetching with isLoading

- components/chat/ActiveWordsModal.tsx
- components/chat/ChatHeader.tsx
- components/chat/ChatMessageComponent.tsx
- components/chat/api.ts
- components/word-bank/WordInfoCard.tsx
- redux/chatSelectors.ts
- screens/chat/ChatScreen.tsx
- Fix active words modal not fetching active words properly
- Highlight active words on chat messages
- Signify active words on definition cards
> feat(LINGUIST-451) Active words improvements

- components/common/form/ItemGroup.tsx
- components/stats/LoggedDatesCalendar.tsx
- components/stats/WordLearningStatusBarChart.tsx
- components/user/constants.ts
- components/user/onboarding/PostRegistrationConversation.tsx
- components/user/onboarding/UserInfoForm.tsx
- Add skeleton to stats
- Post-reg screen minor updates
- Remove english level from profile
> feat(LINGUIST-379 & LINGUIST-437) General UI/UX improvements

- components/chat/ChatHeader.tsx
- components/chat/ChatMessageComponent.tsx
- components/stats/RefetchButton.tsx
- components/utils.ts
Changed the timestamps on the chat screen and the home screen (under stats) to hh:mm (24 hour view).
> feat(LINGUIST-488): Timestamps are shown as hh:mm

- components/common/form/PrimaryDatePicker.tsx
- components/user/onboarding/UserInfoForm.tsx
Now if no birth date is provided, the screen correctly shows "Pick your birthdate". 
The issue was that new Date(null) gives the Unix Epoch time (1970), **not** a null object.
> fix(LINGUIST-480): Birth date default is not 1970

- components/chat/ChatTextInputContainer.tsx
> refactor(LINGUIST-539): Minor refactor on chat text input container

- components/word-bank/api.ts
- components/word-bank/word-list/WordLists.tsx
- Updating the filtered lists with the newly fetched value (one side effect: filters will be resetted)
> bugfix(LINGUIST-536): Fix word lists not being updated after a new word list is added

- components/gamification/streak/ChatStreakView.tsx
- components/stats/LoggedDatesCalendarFromData.tsx
- components/stats/WordLearningStatusBarChartFromData.tsx
- components/user/profile/friends/FriendProfile.tsx
- components/user/profile/friends/FriendsList.tsx
- screens/user/FriendRequestsScreen.tsx
- screens/user/FriendsScreen.tsx
Added shimmering placeholders and loading indicators to friend profile. 
I also made some minor style changes to friends and friend requests screen, I hope it looks good on every screen 
Placeholders on friend profile:
Friends screen (margins changed): 
Requests screen (margins changed):
> feat(LINGUIST-483): Added placeholders to friend profile

- components/chat/conversations/ConversationsWrapper.tsx
- components/common/FloatingButton.tsx
- components/word-bank/word-list/WordLists.tsx
- navigation/ChatStackNavigator.tsx
- screens/word-list/WordListDetailsScreen.tsx
Now the + buttons say "Add List", "Add Word" or "Chat Bots" next to the icon.
> feat(LINGUIST-562): Add text to floating button

- components/gamification/experience/FriendExperienceBar.tsx
- components/user/userApi.ts
Leaderboard update fixed by keepUnusedDataFor: 0 - now updates after xp increases
> fix(LINGUIST-561): Leaderboard update fix

- components/gamification/store/StoreWrapper.tsx
- components/word-bank/api.ts
- components/word-bank/word-list/types.ts
- components/word-bank/word-list/words/WordDetailsCollapse.tsx
- screens/word-list/WordListDetailsScreen.tsx
Added a button to delete words in the detailed word list screen. 
It would be better to merge this after [this PR](https://github.com/LinguistAI/user/pull/78) since it solves an issue with active word deletion.
> feat(LINGUIST-485): Delete word button 

- package-lock.json
- package.json
Updated the dependency for the checkbox.
> fix(LINGUIST-495): Updated dependencies 

- components/quiz/QuizController.tsx
- components/quiz/QuizQuestion.tsx
> fix(LINGUIST-585): Disallow multiple answers
